language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "aA7AzB6UM/UEkzCEMY/0o7HwScWNagA19FTK6nHXU5DG8aR2NYqtj/yUBTXqQsByCyw6qqayYAnYPu1Mp6sBOeAf1tC+f8thdXnDa4ItX3TsTdIBADSNGw9Rx+Uv8K5fVXkrzZdmDN5Az/KrFczwUdvabdc/9XhhtvzUQqC96EblWCAhA5m1KA+A2PTEGX94j4NdkWOBZWeEzibNytCTbeIJPjtCreCuNw71xPHl/MO+WxGaAHGh8kcUuerwf6yAb61F7+/GAetxZwfjGjG6BaqtmBK4jaKBLf+PFKahcFJ+SFlxWo2/imeBKmuBmLf5TwleVM722MYJ1yP0K1tYgRJgGGlnQMO/jyfN2HqmM8KTuTwzhXfZbM3gvinDSg3oYBdZRaAnR7/ANxf6uQPlpxca1ZKXn3RRu7sz2wbh5/GZE2FUTA4+AGXCmJ2ddIdv8wotusgGijA5mijN/LXRcJQh7Qlq6kSTr98MRNhRoePja1UBp/63P+q/b1lJrKJPYVERmJ90TGBJlcpC/MKTcFgfPBrmYU+7Woikfu+ZNUb4HMbhzJ0FuKiC3+RzJKK8fgDJjayhrb5dt+dLyD2h1jOftBOw/EyGDpDgNfCtRLCwQnQNicV9bB7xEyVrpzYMPDr2udzN7kFItAdrRQEZGxKk3QvHmCdlPA6tzHL9/Fg="
    # SNYK_API_TOKEN=[secure]
    - secure: "KnX5prNfKv2EfBZ5yfo8tSHV50b4VILYXT3zTStSkODgh9a1EB3fpXJkTWSgJsWGInYeCr7rIThu0/PAObBzgQzzavGX3voURVg3+BYABnvqocILCNJfn6kacxTKLClnFJoq+GN5zEpAGgoA6uyIxDFmavYJmLzdeOvncJ3HO92EcovBcZobsO/1tFvjK//iemSXc5loaMRyY1Hxk72TiblFRTEHPecIAeObN3PLFZHmR/b/bO/ucAvEMOlCrCfFiQzgSgVo4oWbztiLv6OP3RR9e54SZuUstyigCOhIfDqCUBU1pnwsbkNZu0qIRhsmrQReEXT4Aur/5/EWxP16PFPVXriWWTxLiN7oke+r6pozsAyuB5tUN5HEhBifMG/4+UwTfb8ST78cvmnDTE0b3yDic3DtyxDSdFupxK3+E51+ELkinf98n+SbJJKnFtQfNfRTU6tbKhmXaSiqFhpkkMoz2gs0U1JXGD4V6DHlwyHn7+kxuyn5Bplmvf/Y8CpC2yvqiL3kQ/jLRmOw1CyrSZP3/oCXxu2ryYw4bVgXL81SVBpUYQE5iN6EpqCl8XdUjzi2ZU7sAdXsmWl1hSYuG5FSc9f2Q1YWl8XOE03xdIdRSwZPG4Goot0tGVDCIywUiKhvQyCDnkjHQcNAIazPhGsZYzSxDCjIVQwDGS2646U="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "wPu7k+7am3D3pLezpbdPKKkDzk+5VrmuyRmqn5upLcHKXI4hGpoRDYiEF5eGlVVah0qGdT0cbqCJf8QtZDmSF3CARMyMvnZFg4GfdvRxcFCYP6+8DTi0khBFUlD59SoYOn9D9ST0KviIA7My9izsyJHyVj7YqxTbr6Ru66MEaga0NdwhKn50qhWniNd8PWx52GFtyr/4iDLP+W3k5MLnoAz2VU+ya6RBXzTAZ+JaK6y269O4rhVnhhdtsuDkhrWDWcgt1895Ln8DGdLolWA0UvZzwjD2g/Fq0eqbCvMYxhVfW2PtMmDZvU3y5l1T3TQL5ADc6YTFWuAQvX7784GGT2D9wAL5TrHnW9NG6+v8Fu6WWuBiWbGMLRpzR6MwUoBgmNByztJZNtwlMbMWppEkQucN2jb3Jaf1ePuwq2gbtsW7vWmTbEc/lq1/sAWnn98bgG6iqWs+N/4e+zW1mfMVGNlszgFx/VgeYquXNsgWvMOwaOElaaIJ15+zaMl5bQL/UVVJg2LivVg7c1SrOHI//wPG/6vgfZhTOjH7eA49C80QIM6M/niLGefkb9q1Lt2rAyhRX3rbLMKbnpB+1GR8SbtedUFPMQktpxu5wkJwpywniva2cMwrxHAD2AqCKYgmW86l2m0jECeQFt7i0WLr98eJydVMQSoGakQTdmmO/7k="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "UxQXlHdaNzmZg2JMwzjmDqoPYDHVbLP5x4dmlL5h5gVbmimqDZiO+hvzFK8jIJQtP7vWtHHYzg8SP0gVAmNWWP8PB8uX6OPjC9IsCweos/JuVPvoUUyiT1nfkL0FnI4JgRLNDk/WbB54Ue8jz1jslSsL6p9nFs+E875ZpDFBOi7HkFF5OVFTTmiaf/3djbEz3tMRMpweQnV/csnIe7i/pa+sz3UfpybEpShDm/ftXlsIVXst2Fn8HdSV1H4u9pmX0rdcGjMKiypFGq3Q5wbqpmnWojAlkc9R4/XyaDzc/RBjyZLcEPGK50Vq37c6TDfq53iAyOZnfz3ZuXKM5hlY9JbA3zsjdv91i7XNU0JmPwqnDidb1fVyRBp1uJW6tBcyOskUgeMkpN/xQYaLY4XrQur0SeuUxNsbRculYI/nfC38nu5ukwvbwtK1+yubePErZ2xMSY56tV6o+6kiXHoFMeuOBMiJn3Osah/8BcP8Hkbh2HYInQNkb06KCZ6ygOnpeZ9uGeWmPjDPPWlXYXkui+Nh6Q7FhZo7WCcZB9omtCKRwjwPSrNNBKNKyfxGiwwic7Sx88x7m5Hw9+kwmqn58lcoQbSKRruibAxqvWHsATOiteyy8Dhnei29Pj4eNbtfJ03Yb//WLysTVuMZVBiP1QYdpa9Xenkx8kfVs/bzIbc="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "e6JbiVbPhY66Ys5AAka+oPzy3sh4/OLXl8s+CesNbHCVn9aGCiTQejM2yReJwkby0q0NMkhWY29kXnqnOOvsEapKOpHg5kB/2HN1dHo3ZEQv9UGGI2W1Me4NqEVvg8Mla2D680S2UAkyQyGyTZYTmdsZWTiVj57fcaTbNh4bH8pj/clmWBluRJGhOmwstiMX5xdpwzghjPCsy6WjnRwNM8aVuHDYFNzfjJWuOlmiUpZb9o8SjerEjd33y+d286CgStbPwFg/uIa+tBdcntazn9FyuEHVy07HC5GBAx6L9+u+ryfjlH3+PRSmFrKAZHwyWiFPanQAyVPjoGEzeSU7v4OpLWbqbJgZQ+RLhE6CJotz9KEeTecxzlKP4A6z2/QvfMDA0D8qko1fE2lFmc4WMcDIy/f8eIZn5ELluZeAXqkXncjMV7QH+9O3yp+CKNrPRbhUNCpxb+l39NyvjhEwt1XJ/FXgkU5TnLxnWyHln7g/exsyqz/APmJKNkqYlj6QU2Inr2+rwDFJXSekDmU0JQcrzlyID7/hzmJh61lZmgbhX2xMft1PQKfFM0cP6XvnkSrL8v0BZIAflV42fR5m8Lw68GzN2dEIy2vmVQqpuuTrItzE4i16AvJGI6ZZqRwxHXtvsCiUT0ZzQQz1CoB9UWhacygrsE4gGfSsjvUSrI8="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
