language: node_js
sudo: required
node_js:
  - '4.3'
  - '6.2'
cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - cp bin/test/package.json .
after_success:
  - npm run coverage
env:
  matrix:
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
notifications:
  slack:
    secure: 
      SVqtHrZnE8uF8gW1eocowc0mBVmrqEA7sUTMN0/64lQIp0l4i4y5QyjpY4MWLmGpz+mXBiddW2Trgf56MMggYn1YbBAD99UUUAq8ew82ApEB2EXXKPXJaCHCKLSav0VureRHniQqYIgp6ZVHbTAx3tGKIJ70F2CAIUVwmpkNxHJ/ecdz5GTTtPKxVn4AJKx5+IflnJEg7d122ayL/WMepwbPTzZJto1hCyKuspdw8H9YL+QsJUzUo4q0Q8B0PbXvkSBmc7g0qIerr/gd8eIvXwyr0qAL6C61pRPGGA6uvACV50muT/ear0ZwomX0EJS9Kq5iFGu30sgxLTgZjrV+5jqxsnjODYHo7d/FcE5mdgYK2Trr1+KczlhRH/km85PahK7iQYq0p3LeE8qkh1fp4AqOMMqoBc0mwa38DBSnBRArcK736SCxLMr6+t3jrzPzF7iIhP6hCfKEYxHu2gxmoPgEbwOpk5eQs24H8+rnLkjVGnJ+8nzjXrHDc4v/jr2BwsldozDzebNkP5HB1hDsfvZBq9ZW9GEebWEBIbs7jXy7tKHN7CM6EZKftaTz0gsj3JJBjDuEgiADtcaEIuLve7Ioe0JhbPugwBh9d7/5oQEb++JPbWFHsU8domUO9nN9CJm/dblcBMFfiX4C6oXRwLhqyrJJ2jY0PD5bXBtooMM=
